import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { urlList } from "./util/UrlList";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          {Object.values(urlList).map((e, idx) => {
            return (
              <Link key={idx} href={e.url}>
                {e.labelName}
              </Link>
            );
          })}
        </div>
        {children}
      </body>
    </html>
  );
}
